theme: jekyll-theme-modernist
title: HexaEight Documentation
description: Documentation
logo: https://www.hexaeight.com/assets/images/helogo-178x79.jpg
show_downloads: false
github:
    is_project_page: false
